import express from "express";
import { createServer as createViteServer } from "vite";
import axios from "axios";
import cookieParser from "cookie-parser";
import fs from "fs/promises";
import path from "path";
import { Octokit } from "octokit";

async function startServer() {
  const app = express();
  const PORT = 3000;

  app.use(express.json());
  app.use(cookieParser());

  // GitHub OAuth Configuration
  const GITHUB_CLIENT_ID = process.env.GITHUB_CLIENT_ID;
  const GITHUB_CLIENT_SECRET = process.env.GITHUB_CLIENT_SECRET;

  // 1. Get Auth URL
  app.get("/api/auth/github/url", (req, res) => {
    if (!GITHUB_CLIENT_ID) {
      return res.status(500).json({ error: "GITHUB_CLIENT_ID not configured" });
    }
    
    // Use APP_URL environment variable provided by the platform
    const appUrl = process.env.APP_URL || `https://${req.get("host")}`;
    const redirectUri = `${appUrl.replace(/\/$/, "")}/auth/github/callback`;
    
    const url = `https://github.com/login/oauth/authorize?client_id=${GITHUB_CLIENT_ID}&redirect_uri=${encodeURIComponent(redirectUri)}&scope=repo,user`;
    res.json({ url });
  });

  // 2. OAuth Callback
  app.get("/auth/github/callback", async (req, res) => {
    const { code } = req.query;
    if (!code) return res.status(400).send("No code provided");

    try {
      const response = await axios.post(
        "https://github.com/login/oauth/access_token",
        {
          client_id: GITHUB_CLIENT_ID,
          client_secret: GITHUB_CLIENT_SECRET,
          code,
        },
        { headers: { Accept: "application/json" } }
      );

      const { access_token } = response.data;
      
      // Send success message and token to parent window
      res.send(`
        <html>
          <body>
            <script>
              if (window.opener) {
                window.opener.postMessage({ 
                  type: 'GITHUB_AUTH_SUCCESS', 
                  token: '${access_token}' 
                }, '*');
                window.close();
              } else {
                window.location.href = '/';
              }
            </script>
            <p>Authentication successful. You can close this window.</p>
          </body>
        </html>
      `);
    } catch (error) {
      console.error("GitHub OAuth error:", error);
      res.status(500).send("Authentication failed");
    }
  });

  // 3. Push to GitHub
  app.post("/api/github/push", async (req, res) => {
    const { token, repoName } = req.body;
    if (!token || !repoName) return res.status(400).json({ error: "Missing token or repoName" });

    try {
      const octokit = new Octokit({ auth: token });
      
      // Get user info
      const { data: user } = await octokit.rest.users.getAuthenticated();
      
      // Create repository
      let repo;
      try {
        const { data } = await octokit.rest.repos.createForAuthenticatedUser({
          name: repoName,
          description: "Gas Installation Protocol App - Generated by AI Studio",
          private: false,
          auto_init: true,
        });
        repo = data;
      } catch (e: any) {
        if (e.status === 422) {
          // Repo already exists, let's try to use it
          const { data } = await octokit.rest.repos.get({
            owner: user.login,
            repo: repoName,
          });
          repo = data;
        } else {
          throw e;
        }
      }

      // Helper to read all files recursively (excluding node_modules, dist, etc.)
      const getFiles = async (dir: string): Promise<string[]> => {
        const entries = await fs.readdir(dir, { withFileTypes: true });
        const files = await Promise.all(
          entries.map((entry) => {
            const res = path.resolve(dir, entry.name);
            if (entry.isDirectory()) {
              if (["node_modules", ".git", "dist", ".next"].includes(entry.name)) return [];
              return getFiles(res);
            }
            return [res];
          })
        );
        return files.flat();
      };

      const allFiles = await getFiles(process.cwd());
      const rootPath = process.cwd();

      // Push files one by one (simplified for this demo)
      // In a real app, you'd use a tree commit, but for a small app this is fine
      for (const filePath of allFiles) {
        const relativePath = path.relative(rootPath, filePath);
        const content = await fs.readFile(filePath, "utf8");
        
        try {
          // Check if file exists to get its SHA
          let sha;
          try {
            const { data } = await octokit.rest.repos.getContent({
              owner: user.login,
              repo: repoName,
              path: relativePath,
            });
            if (!Array.isArray(data)) sha = data.sha;
          } catch (e) {}

          await octokit.rest.repos.createOrUpdateFileContents({
            owner: user.login,
            repo: repoName,
            path: relativePath,
            message: `Upload ${relativePath}`,
            content: Buffer.from(content).toString("base64"),
            sha,
          });
        } catch (e) {
          console.error(`Failed to push ${relativePath}`, e);
        }
      }

      res.json({ success: true, url: repo.html_url });
    } catch (error: any) {
      console.error("GitHub push error:", error);
      res.status(500).json({ error: error.message || "Failed to push to GitHub" });
    }
  });

  // Vite middleware for development
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    app.use(express.static("dist"));
    app.get("*", (req, res) => {
      res.sendFile(path.resolve("dist/index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://localhost:${PORT}`);
  });
}

startServer();
